# Generated by Django 4.2.17 on 2025-01-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('task', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('priority', models.BooleanField()),
            ],
        ),
    ]
