# Generated by Django 4.2.17 on 2025-01-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailytaskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
    ]
