# Generated by Django 4.2.17 on 2025-01-15 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailytaskapp', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytaskmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailytaskapp.user'),
        ),
    ]
