# Generated by Django 4.2.17 on 2025-01-15 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailytaskapp', '0003_alter_dailytaskmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytaskmodel',
            old_name='user',
            new_name='user_id',
        ),
    ]
