# Generated by Django 3.2.19 on 2025-01-10 08:45

import authorapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorcls',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=authorapp.models.author_image_file_path),
        ),
    ]
